// src/components/SocialLinks.vue
<template>
  <ul class="social-links d-inline-flex list-unstyled">
    <li v-for="item in socialLinks" :key="item.url">
      <a
        :href="item.url"
        class="external"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="{{link.label}}"
      >
        <Icon :icon="item.iconClass" />
      </a>
    </li>
  </ul>
</template>

<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { SOCIAL_LINKS } from "../const.ts";

const socialLinks = SOCIAL_LINKS;
</script>

// src/components/SocialLinks/index.tsx
import React from "react"

import config from "../../../data/siteConfig"

const SocialLinks: React.FC = () => {
  const { userLinks } = config
  return (
    <ul className="social-links d-inline-flex list-unstyled">
      {userLinks.map(link => {
        return (
          <li key={link.label}>
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={link.label}
            >
              <i className={link.iconClassName} />
              <span className="d-none">{link.label}</span>
            </a>
          </li>
        )
      })}
    </ul>
  )
}

export default SocialLinks
