// src/components/Bio.vue
<template>
  <div id="about" />
  <section class="section modular-recent">
    <div class="container grid-md">
      <div class="columns">
        <div class="column col-3 col-md-12 header-col">
          <h4>
            <span>{{ about.title }}</span>
          </h4>
        </div>
        <div class="column col-9 col-md-12 main-col">
          <div class="columns item">
            <p class="column col-12 padded" v-html="about.shortInfo" />
            <div class="column col-4 col-md-12">
              <NuxtLink to="/about" class="btn btn-lg">
                More things about me...
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const about = useAppConfig().about;
</script>

// src/components/bio.tsx
import { Link } from "gatsby"
import { AboutData } from "models/about"
import React from "react"

const Bio = ({ info }: AboutData) => {
  return (
    <>
      <div id="about" />
      <section className="section modular-recent">
        <div className="container grid-md">
          <div className="columns">
            <div className="column col-3 col-md-12 header-col">
              <h4>
                <span>About me</span>
              </h4>
            </div>
            <div className="column col-9 col-md-12 main-col">
              <div className="columns item">
                <p
                  dangerouslySetInnerHTML={{ __html: info.shortInfo }}
                  className="column col-12 padded"
                />
                <div className="column col-4 col-md-12">
                  <Link to="/about" className="btn btn-lg">
                    More things about me...
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default Bio
