// components/Footer.vue
<template>
  <section id="footer" class="section">
    <section class="container grid-lg">
      <SocialLinks />
    </section>
    <section class="container grid-lg">
      <ul class="copyright d-inline-flex list-unstyled">
        <li>© {{ new Date().getFullYear() }} Rubén Rodríguez</li>
        <li>
          <ul class="d-inline-flex list-unstyled">
            <li v-for="item in footerLinks" :key="item.url">
              <NuxtLink :to="item.url" class="external">
                {{ item.title }}
              </NuxtLink>
            </li>
          </ul>
        </li>
      </ul>
    </section>
  </section>
</template>

<script setup lang="ts">
const footerLinks = useAppConfig().footerLinks;
</script>

// src/components/Footer.tsx
import { Link } from "gatsby"
import React from "react"
import config from "../../content/data/siteConfig.json"
import SocialLinks from "./SocialLinks"

const Footer = () => {
  const { footerLinks } = config
  return (
    <section id="footer" className="section">
      <section className="container grid-lg">
        <SocialLinks />
      </section>
      <section className="container grid-lg">
        <ul className="copyright d-inline-flex list-unstyled">
          <li>© {new Date().getFullYear()} Rubén Rodríguez </li>
          <li>
            <ul className=" d-inline-flex list-unstyled">
              {footerLinks.map((link) => {
                return (
                  <li key={link.url}>
                    <Link to={link.url} className="external">
                      {link.title}
                    </Link>
                  </li>
                )
              })}
            </ul>
          </li>
        </ul>
      </section>
    </section>
  )
}

export default Footer
