// components/HeroTyped.vue
<template>
  <section
    class="section modular-hero hero"
    :class="
      heroClasses +
      (subtitle ? ' title-h1h2' : '') +
      (smallHeadings ? ' small-headings' : '') +
      (isParallax ? ' parallax' : '')
    "
    :style="{
      backgroundImage: bagroundImageUrl,
      backgroundPositionY: position + 'px',
    }"
  >
    <div class="image-overlay" />
    <div class="container grid-md" :class="textAlign">
      <h1><span id="typed"></span></h1>
      <h2 v-if="props.subtitle">{{ props.subtitle }}</h2>
      <p v-if="props.text">
        <span v-html="props.text" />
      </p>
    </div>
    <SocialLinks v-if="social" />
    <i
      v-if="arrow"
      id="to-start"
      class="pulse fa fa-angle-down"
      :on-click="toStart"
      :on-keydown="handleKeyDown"
      role="button"
      tabIndex="{0}"
      aria-label="Go to content"
    >
      <span class="d-none">Go to content</span>
    </i>
  </section>
</template>

<script setup lang="ts">
import Typed from "typed.js";
const position = ref(0);

const props = defineProps<{
  title?: string[];
  subtitle?: string;
  image?: string;
  text?: string;
  social?: boolean;
  isParallax?: boolean;
  arrow?: boolean;
  heroClasses?: string;
  textAlign?: string;
  smallHeadings?: boolean;
}>();

// Default props
const title = ref(props.title || [""]);
const image = ref(props.image || "/img/hero-default.jpg");
const social = ref(props.social || false);
const isParallax = ref(props.isParallax || true);
const arrow = ref(props.arrow || true);
const heroClasses = ref(
  props.heroClasses || "text-light hero-tiny overlay-dark-gradient"
);
const textAlign = ref(props.textAlign || "text-center");
const smallHeadings = ref(props.smallHeadings || false);
let typed: any;

const $img = useImage();
const bagroundImageUrl = computed(() => {
  const imgUrl = $img(image.value, { width: 1600 });
  return `url('${imgUrl}')`;
});

const parallax = () => {
  position.value = window.scrollY * 0.3;
};

const toStart = () => {
  const start = document.getElementById("start")!.offsetTop;
  const offset = 45;
  window.scroll({ top: start - offset, left: 0, behavior: "smooth" });
};

const handleKeyDown = (ev: any) => {
  // M key
  if (ev.keyCode === 67) {
    toStart();
  }
};

onMounted(() => {
  window.addEventListener("scroll", parallax);
  typed = new Typed("#typed", {
    strings: props.title,
    typeSpeed: 50,
    backSpeed: 10,
    backDelay: 7000,
    cursorChar: "_",
    loop: true,
  });
  typed.start();
});

onUnmounted(() => {
  window.removeEventListener("scroll", parallax);
  typed.destroy();
});
</script>

// src/components/HeroTyped.tsx
import { HeroData } from "../models/hero"
import React, { useEffect, useRef, useState } from "react"
import Typed from "typed.js"
import SocialLinks from "./SocialLinks"

const HeroTyped = ({
  title = null,
  subtitle,
  text,
  image,
  social = false,
  isParallax = true,
  arrow = true,
  classes = "text-light hero-tiny overlay-dark-gradient",
  textAlign = "center",
  smallHeadings = false,
}: HeroData) => {
  const [position, setPosition] = useState(0)

  const parallax = () => {
    setPosition(window.scrollY * 0.3)
  }

  const toStart = () => {
    const start = document.getElementById("start")!.offsetTop
    const offset = 45
    window.scroll({ top: start - offset, left: 0, behavior: "smooth" })
  }

  const handleKeyDown = (ev: any) => {
    // M key
    if (ev.keyCode === 67) {
      toStart()
    }
  }

  useEffect(() => {
    window.addEventListener("scroll", parallax)
    return () => {
      window.removeEventListener("scroll", parallax)
    }
  }, [])

  const typeTarget = useRef(null)

  useEffect(() => {
    const typed = new Typed(typeTarget.current!, {
      strings: title,
      typeSpeed: 50,
      backSpeed: 10,
      backDelay: 7000,
      cursorChar: "_",
      loop: true,
    })

    return () => {
      typed.destroy()
    }
  }, [])

  return (
    <>
      <section
        className={`section modular-hero hero ${
          subtitle && "title-h1h2"
        } ${classes} ${isParallax && "parallax"} ${
          smallHeadings && "small-headings"
        }`}
        style={{
          backgroundPositionY: position,
          backgroundImage: `url(${image})`,
        }}
      >
        <div className="image-overlay" />
        <div className="container grid-md" style={{ textAlign }}>
          {title && (
            <h1>
              <span ref={typeTarget} />
            </h1>
          )}
          {subtitle && <h2>{subtitle}</h2>}
          {text && (
            <p>
              <span dangerouslySetInnerHTML={{ __html: text }} />
            </p>
          )}
        </div>
        {social && <SocialLinks />}
        {arrow && (
          <i
            id="to-start"
            className="pulse fa fa-angle-down"
            onClick={toStart}
            onKeyDown={handleKeyDown}
            role="button"
            tabIndex={0}
            aria-label="Go to content"
          >
            <span className="d-none">Go to content</span>
          </i>
        )}
      </section>
    </>
  )
}

export default HeroTyped
