// src/components/Resume.vue
<template>
  <div id="resume" />
  <section class="section modular-resume bg-gray">
    <section class="container grid-sm">
      <div
        :class="`columns ${section.cssClass}`"
        v-for="section in resume"
        :key="section.id"
      >
        <div class="column col-3 col-md-12 header-col">
          <h4>
            <span>{{ section.title }}</span>
          </h4>
        </div>
        <div class="column col-9 col-md-12 main-col">
          <div
            class="columns item"
            v-for="item in section.items"
            :key="item.id"
          >
            <div class="column col-12">
              <h4 v-if="item.title">{{ item.title }}</h4>
              <p class="info" v-if="item.info">
                {{ item.info }} <span>•</span>{{ " " }}
                <em class="date">{{ item.date }}</em>
              </p>
              <p v-if="item.description" v-html="item.description" />
              <ul class="skill-list" v-if="item.skillList">
                <li v-for="skill in item.skillList" :key="skill">
                  <span class="skill">
                    <Icon :icon="skill.icon" />
                    <span>{{ skill.name }}</span>
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>
</template>

<script setup lang="ts">
import { RESUME } from "../const.ts";
import { Icon } from "@iconify/vue";

const resume = RESUME;
</script>

// src/components/Resume.tsx
import React from "react"
import { ResumeData } from "../models/resume"

const Resume = ({ info }: ResumeData) => {
  return (
    <>
      <div id="resume" />
      <section className="section modular-resume bg-gray">
        <section className="container grid-md">
          {info.map((section) => (
            <div className={`columns ${section.cssClass}`} key={section.id}>
              <div className="column col-3 col-md-12 header-col">
                <h4>
                  <span>{section.title}</span>
                </h4>
              </div>
              <div className="column col-9 col-md-12 main-col">
                {section.items.map((item) => (
                  <div className="columns item" key={item.id}>
                    <div className="column col-12">
                      <h4>{item.title}</h4>
                      <p className="info">
                        {item.info} <span>•</span>{" "}
                        <em className="date">{item.date}</em>
                      </p>
                      <p
                        dangerouslySetInnerHTML={{ __html: item.description }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </section>
      </section>
    </>
  )
}

export default Resume
