// src/components/Tags.tsx
import { Link } from "gatsby"
import React from "react"

interface Props {
  items: Array<string>
}

const Tags = ({ items }: Props) => {
  return (
    <span className="tags">
      {items.map((tag) => (
        <Link
          to={`/blog/tag:${tag.toLowerCase()}`}
          key={tag}
          className="label label-rounded"
        >
          {tag}
        </Link>
      ))}
    </span>
  )
}

export default Tags

// src/components/Tags.vue
<template>
  <span class="tags">
    <a
      v-for="tag in items"
      :href="`/blog/tag/${tag.replace(/\s/g, '-').toLowerCase()}`"
      :key="tag"
      class="label label-rounded"
    >
      {{ tag }}
    </a>
  </span>
</template>

<script setup lang="ts">
defineProps<{
  items: string[];
}>();
</script>
